language: rust

notifications:
  slack:
    rooms:
      secure: aIMgngD8m6rnjeI8whJJIBtKeDg5prxSxyeQJcRwShzpZwIgemh9TNvcSRMftuQ0bJ3XjhFY8sViha856yzlPTidec6wdhlYRs+ZzVUt7W+yNVZCsMZ0Av8O+RomfM0HX4E1jlff6qA+mEc2LZB740Nr23W1UVejU5BpbDlELHPElC87yQBGNU316wjfgGe+dYHB56wKBoYalgGhWzkKMwqEiMT66SdGYRFGFveeoYVRskKh/aQ3MdwoUHboClgIqL4O5czvQ17THSnbYXBEm5LhTPNrXruSur3R7IBG6MRTOkyWUezm3pPJqRWNoSg7JJ22cqzp4mvFfV6dpqYK77gq5BiQpRFfKjQyMprezLkhXA43WCfFJznaVzoR0UTI6pAf71wLdJSjYqDrOWLJFbDV41K9TxGOvM94hbNGQVbcaYAAwfrVZBGFO9HLjuGlYaPMQ62DWj0inAghRC6o0CFsRQyCWU024IC37vOsYRw3itQoMu6fZpAEEOK2MXzQGc9Co5krs9+8B/jrsDaIjFl0pL/TUrG6AWAyvwnP2p34oC8iKQSyua2fd8IGRgSIG+w5YJsR1q5AZGFYCqFsKBEPAJYrS1mPQgco0Zsz3UMNnOCxbK786EWZ2cl6uQNXX+r+zMEplG9KukhwefLdTa04NVMT0/8CpVK6oI4kjfY=
